song_dict = [
    ["Pink Pony Club", "Chappell Roan", "Rise and Fall of a Midwest Princess", "Pop"],
    ["Red Wine Supernova", "Chappell Roan", "Rise and Fall of a Midwest Princess", "Pop"],
    ["Casual", "Chappell Roan", "Rise and Fall of a Midwest Princess", "Pop"],
    ["Super Graphic Ultra Modern Girl", "Chappell Roan", "Rise and Fall of a Midwest Princess", "Pop"],
    ["Naked in Manhattan", "Chappell Roan", "Rise and Fall of a Midwest Princess", "Pop"],

    ["The Queen is Dead", "The Smiths", "The Queen is Dead", "Alternative Rock"],
    ["Frankly, Mr. Shankly", "The Smiths", "The Queen is Dead", "Alternative Rock"],
    ["I Know It's Over", "The Smiths", "The Queen is Dead", "Alternative Rock"],
    ["Cemetry Gates", "The Smiths", "The Queen is Dead", "Alternative Rock"],
    ["Bigmouth Strikes Again", "The Smiths", "The Queen is Dead", "Alternative Rock"],

    ["All-American Bitch", "Olivia Rodrigo", "Guts", "Pop Rock"],
    ["Vampire", "Olivia Rodrigo", "Guts", "Pop Rock"],
    ["Lacy", "Olivia Rodrigo", "Guts", "Pop Rock"],
    ["Ballad of a Homeschooled Girl", "Olivia Rodrigo", "Guts", "Pop Rock"],
    ["Making the Bed", "Olivia Rodrigo", "Guts", "Pop Rock"],

    ["The Width of a Circle", "David Bowie", "The Man Who Sold the World", "Glam Rock"],
    ["All the Madmen", "David Bowie", "The Man Who Sold the World", "Glam Rock"],
    ["Black Country Rock", "David Bowie", "The Man Who Sold the World", "Glam Rock"],
    ["After All", "David Bowie", "The Man Who Sold the World", "Glam Rock"],
    ["Running Gun Blues", "David Bowie", "The Man Who Sold the World", "Glam Rock"],

    ["Mojo Pin", "Jeff Buckley", "Grace", "Alternative Rock"],
    ["Grace", "Jeff Buckley", "Grace", "Alternative Rock"],
    ["Last Goodbye", "Jeff Buckley", "Grace", "Alternative Rock"],
    ["Lilac Wine", "Jeff Buckley", "Grace", "Alternative Rock"],
    ["So Real", "Jeff Buckley", "Grace", "Alternative Rock"],

    ["Bohemian Rhapsody", "Queen", "A Night at the Opera", "Rock"],
    ["Love of My Life", "Queen", "A Night at the Opera", "Rock"],
    ["You're My Best Friend", "Queen", "A Night at the Opera", "Rock"],
    ["Death on Two Legs", "Queen", "A Night at the Opera", "Rock"],
    ["'39", "Queen", "A Night at the Opera", "Rock"],

    ["Vision of Love", "Mariah Carey", "Mariah Carey", "Pop"],
    ["Love Takes Time", "Mariah Carey", "Mariah Carey", "Pop"],
    ["Someday", "Mariah Carey", "Mariah Carey", "Pop"],
    ["I Don't Wanna Cry", "Mariah Carey", "Mariah Carey", "Pop"],
    ["Vanishing", "Mariah Carey", "Mariah Carey", "Pop"],

    ["Sweet Adeline", "Elliott Smith", "XO", "Indie Rock"],
    ["Waltz #2 (XO)", "Elliott Smith", "XO", "Indie Rock"],
    ["Baby Britain", "Elliott Smith", "XO", "Indie Rock"],
    ["Pitseleh", "Elliott Smith", "XO", "Indie Rock"],
    ["Independence Day", "Elliott Smith", "XO", "Indie Rock"],

    ["Papaoutai", "Stromae", "Racine Carrée", "Electronic"],
    ["Tous les mêmes", "Stromae", "Racine Carrée", "Electronic"],
    ["Formidable", "Stromae", "Racine Carrée", "Electronic"],
    ["Carmen", "Stromae", "Racine Carrée", "Electronic"],
    ["Ta fête", "Stromae", "Racine Carrée", "Electronic"],

    ["You Oughta Know", "Alanis Morissette", "Jagged Little Pill", "Alternative Rock"],
    ["Ironic", "Alanis Morissette", "Jagged Little Pill", "Alternative Rock"],
    ["Hand in My Pocket", "Alanis Morissette", "Jagged Little Pill", "Alternative Rock"],
    ["You Learn", "Alanis Morissette", "Jagged Little Pill", "Alternative Rock"],
    ["Head over Feet", "Alanis Morissette", "Jagged Little Pill", "Alternative Rock"],

    ["Fast Car", "Tracy Chapman", "Tracy Chapman", "Folk Rock"],
    ["Talkin' 'bout a Revolution", "Tracy Chapman", "Tracy Chapman", "Folk Rock"],
    ["Baby Can I Hold You", "Tracy Chapman", "Tracy Chapman", "Folk Rock"],
    ["Mountains o' Things", "Tracy Chapman", "Tracy Chapman", "Folk Rock"],
    ["For My Lover", "Tracy Chapman", "Tracy Chapman", "Folk Rock"],

    ["Wuthering Heights", "Kate Bush", "The Kick Inside", "Art Rock"],
    ["The Man with the Child in His Eyes", "Kate Bush", "The Kick Inside", "Art Rock"],
    ["Moving", "Kate Bush", "The Kick Inside", "Art Rock"],
    ["Strange Phenomena", "Kate Bush", "The Kick Inside", "Art Rock"],
    ["Them Heavy People", "Kate Bush", "The Kick Inside", "Art Rock"],

    ["Smells Like Teen Spirit", "Nirvana", "Nevermind", "Grunge"],
    ["Come as You Are", "Nirvana", "Nevermind", "Grunge"],
    ["Lithium", "Nirvana", "Nevermind", "Grunge"],
    ["In Bloom", "Nirvana", "Nevermind", "Grunge"],
    ["Polly", "Nirvana", "Nevermind", "Grunge"],

    ["La Vie en Rose", "Édith Piaf", "La Vie en Rose", "Chanson"],
    ["Non, je ne regrette rien", "Édith Piaf", "La Vie en Rose", "Chanson"],
    ["Milord", "Édith Piaf", "La Vie en Rose", "Chanson"],
    ["Hymne à l'amour", "Édith Piaf", "La Vie en Rose", "Chanson"],
    ["Padam... Padam...", "Édith Piaf", "La Vie en Rose", "Chanson"],

    ["Criminal", "Fiona Apple", "Tidal", "Alternative Rock"],
    ["Shadowboxer", "Fiona Apple", "Tidal", "Alternative Rock"],
    ["Sleep to Dream", "Fiona Apple", "Tidal", "Alternative Rock"],
    ["Never Is a Promise", "Fiona Apple", "Tidal", "Alternative Rock"],
    ["Slow Like Honey", "Fiona Apple", "Tidal", "Alternative Rock"],

    ["Rehab", "Amy Winehouse", "Back to Black", "Soul"],
    ["Back to Black", "Amy Winehouse", "Back to Black", "Soul"],
    ["You Know I'm No Good", "Amy Winehouse", "Back to Black", "Soul"],
    ["Love Is a Losing Game", "Amy Winehouse", "Back to Black", "Soul"],
    ["Tears Dry on Their Own", "Amy Winehouse", "Back to Black", "Soul"],

    ["Dog Days Are Over", "Florence and the Machine", "Lungs", "Indie Rock"],
    ["Rabbit Heart (Raise It Up)", "Florence and the Machine", "Lungs", "Indie Rock"],
    ["Kiss with a Fist", "Florence and the Machine", "Lungs", "Indie Rock"],
    ["Cosmic Love", "Florence and the Machine", "Lungs", "Indie Rock"],
    ["Drumming Song", "Florence and the Machine", "Lungs", "Indie Rock"],

    ["No Scrubs", "TLC", "FanMail", "R&B"],
    ["Unpretty", "TLC", "FanMail", "R&B"],
    ["Silly Ho", "TLC", "FanMail", "R&B"],
    ["I'm Good at Being Bad", "TLC", "FanMail", "R&B"],
    ["Dear Lie", "TLC", "FanMail", "R&B"],

    ["A Change Is Gonna Come", "Sam Cooke", "Ain't That Good News", "Soul"],
    ["Another Saturday Night", "Sam Cooke", "Ain't That Good News", "Soul"],
    ["Good Times", "Sam Cooke", "Ain't That Good News", "Soul"],
    ["Tennessee Waltz", "Sam Cooke", "Ain't That Good News", "Soul"],
    ["There'll Be No Second Time", "Sam Cooke", "Ain't That Good News", "Soul"],

    ["Complicated", "Avril Lavigne", "Let Go", "Pop Rock"],
    ["Sk8er Boi", "Avril Lavigne", "Let Go", "Pop Rock"],
    ["I'm with You", "Avril Lavigne", "Let Go", "Pop Rock"],
    ["Losing Grip", "Avril Lavigne", "Let Go", "Pop Rock"],
    ["Mobile", "Avril Lavigne", "Let Go", "Pop Rock"]
]
